version: "3.7"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    user: "0"
    volumes:
      - ${PWD}/certs:/usr/share/elasticsearch/config/certs
      - ${PWD}/instances.yml:/usr/share/elasticsearch/config/certs/instances.yml
      # - type: bind
      #   source: ${PWD}/instances.yml
      #   target: /usr/share/elasticsearch/config/certs/instances.yml
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f /usr/share/elasticsearch/config/certs/instances.yml ]; then
          echo "No instances.yml";
          exit 1
        fi;
        bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
        unzip config/certs/certs.zip -d config/certs;
      '
volumes:
  certs:
    driver: local
