version: '3.6'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    restart: always
    # environment:
      # - TZ=Asia/Shanghai
      # - tz='Asia/Shanghai'
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./../certs:/usr/share/logstash/certs
      - type: bind
        source: ./logstash.yml
        target: /usr/share/logstash/config/logstash.yml
      - type: bind
        source: config.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
      - 9600:9600
     # - 50000:50000
